-- DEPRECADO — 2026-07-25.
--
-- Este archivo dejo de usarse en el pipeline de deploy. El proyecto ahora usa
-- migraciones versionadas de Prisma (prisma/migrations/), aplicadas con
-- `prisma migrate deploy` (script npm db:deploy).
--
-- Todo el contenido acumulado aqui hasta el 2026-07-25 quedo capturado en
-- prisma/migrations/0_baseline/migration.sql (baseline generado por
-- introspeccion de la BD real de produccion, marcado como ya aplicado —
-- no ejecuta nada, es solo el punto de partida del historial de migraciones).
--
-- El archivo original se conserva en
-- prisma/_historico/migrations_pendientes_2026-07-25_superseded.sql
-- como referencia historica.
--
-- A partir de ahora, los cambios de esquema se hacen asi:
--   1. Editar prisma/schema.prisma
--   2. `npx prisma migrate dev --name <descripcion>` en local (genera un
--      nuevo archivo en prisma/migrations/ y lo aplica a tu BD local/dev)
--   3. Commitear la carpeta de migracion generada
--   4. El deploy en Coolify ejecuta `prisma migrate deploy` automaticamente
--      (via npm run start:prod), que aplica solo las migraciones pendientes
--      de forma idempotente y con historial verificable en _prisma_migrations.
